server:
  port: 9090

# starting spring-boot without webserver configuration
#spring:
#  main:
#    web-application-type: none

# conf is per default & not needed
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:customer
    username: user
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
  main:
    web-application-type: servlet